### ISSUE TITLE
docker部署后看不到github登录

### ISSUE THREAD

**Issue by charley008** [ourongxing/newsnow#2]
按文档来部署了docker版，好像没看到github账号登录 。
![屏幕截图 2024-10-24 130355](https://github.com/user-attachments/assets/cb07cac2-3e22-4a63-9baa-ae18662c6849)
是不是还有什么地方需要添加的？
```
services:
  newsnow:
    image: ghcr.io/ourongxing/newsnow:latest
    container_name: newsnow
    restart: always
    ports:
      - '127.0.0.1:4444:4444'
    environment:
      - G_CLIENT_ID=afsdfdasfasdfhFF7fUQAka4P
      - G_CLIENT_SECRET=test485b32e3d46201d8ddd407b03
      - JWT_SECRET=test485b32e3d46201d8ddd407b03
      - INIT_TABLE=
```
